### ISSUE TITLE
(Doc Feedback) Fix Events, Actions and Behaviors

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#100]
"The events that you list are not clearly enough instantaneous. For example, user registration can be an activity or an entity more so than an event. If you want to be sure that you're talking about an event, highlight it's instantaneousness and/or it's being triggered/triggering of actions. For example, "sign up request submitted - the user has just submitted all the data required for the sign up process. This triggers the sending of a confirmation email." If we're talking about events we need them to be instantaneous. "Website loads" has duration (and also a component that's the actor) so it's not an event.
Your actions are all usage of the system-to-be and not actions from the domain. Describe the domain activities also. For example, from the domain perspective that's a set of job seeker professional experiences. If not all of these should appear on every resume, then we need an operation to choose from these experiences.
Behaviors are only behaviors if they are made up of actions and events that are themselves relevant to the domain. The best way to show this, is to actually describe all the actions and events that make up the behavior. "

**Comment by BreannaGSegarra** [comment]
Section revised: https://docs.google.com/document/d/1MM1IqfHtAGnZ4WQDkrljNMihryT9Nigh0CCW0RDD8r8/edit#heading=h.ru7pttyfu2lw
