### ISSUE TITLE
(Doc Feedback) Fix Terminology

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#101]
"Think about the terms used in Narrative such as: journey, career achievements, skills, stage of career, compile experiences, communicate, potential employers, clients, continually update, complete project, acquire skill, transition, role,... then check which of these you do not yet have in your terminology."

**Comment by Axl4767** [comment]
Expanded the Terminology section to include new terms and concepts relevant to the project narrative. This expansion involves the addition of terms such as "Journey," "Career Achievements," "Stage of Career," "Compile Experiences," "Communicate," "Potential Employers/Clients," "Continually Update," "Complete Project," "Acquire Skill," "Transition," and "Role," along with their definitions.
