### ISSUE TITLE
(Doc Feedback) Fix Concept Analysis

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#104]
"You could also identify the separate concepts "selecting information" and "formatting". This would only be an appropriate choice of concepts if you think about the resumes as not necessarily containing all the information that the job seeker has stored. So, if only some of the information gets used in that resume and possibly other information gets used on the next resume, then selecting which information goes onto the resume could be seen as an activity independent of the actual formatting. That "formatting" would then be the activity of choosing where each piece of information should go. But it's also possible that you are looking at the concepts in a different way and with a little more comment/explanation I could follow that view."

**Comment by PinkSylvie** [comment]
@irsaris @Negroni1 @BreannaGSegarra The concept analysis and terminology already had formatting with a similar definition to what the professor gave so I added the concept of selecting information per the professor's explanation and connected it to the rest of the analysis and terminology. Whenever you can could you please review it?
