### ISSUE TITLE
[Lecture Topic Task] QA Stakeholders to explore potential risks and countermeasures regarding those risks in the domain

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#107]
As mentioned in class there are several methods to identify risks. For this task you'll interview potential stakeholders of the project's domain to expore risks our domain could have and see what countermeasures they suggest as well for thse risks.

To complete:
Prepare a set of questions, interview 2-3 stakeholders, and link in a comment of this task a google document that includes the questions you utilized for the interview, the answers the stakeholders gave, and a summarized list of the risks and counermeasures you got from the QAs.

**Comment by irsaris** [comment]
Hello, please suggest urgency and difficulty scores.

**Comment by PinkSylvie** [comment]
@Negroni1 @irsaris I think I'm done with this, [here's ](https://docs.google.com/document/d/14gQP1s7tRlht3BxS_r-tsjgI0axmjZPxQxaOSxP4cWU/edit?usp=sharing) the link with the risks and countermeasures obtained thanks to the QA, the form, and the stakeholder answers. I'll be promptly adding them to the documentation alongside the risks detailed in task #108 to be able to close task #109 Could you review this task to see if it can be closed? Thank you!
