### ISSUE TITLE
[Lecture Topic Task] Identify risks by developing and documenting possible What if risks regarding the domain

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#108]
As discussed in class another method to identify risks is by using elicitation techniques. Develop and utilize scenarios to point out failures from What If questions and risks.

To complete:
Create a list of at least 10 possible what if risky scenarios regarding the project domain and list as well potential countermeasures for them. In a comment of the tasks send a link to the document including this list.

**Comment by irsaris** [comment]
Hello, please suggest urgency and difficulty scores.

**Comment by PinkSylvie** [comment]
@Negroni1 @irsaris I think I'm done with this, [here's](https://docs.google.com/document/d/14gQP1s7tRlht3BxS_r-tsjgI0axmjZPxQxaOSxP4cWU/edit?usp=sharing) the link with the scenario risks and countermeasures. I'm working on adding them to the documentation alongside the risks found in task #107 to complete task #109 
But I'm missing an interview with one more stakeholder. But as soon as I'm done with task #107 I'll inform you as well. Could you review this task to see if it can be closed?

**Comment by irsaris** [comment]
You can close it if you want, if we see something wrong, we'll reopen it.
