### ISSUE TITLE
[Lecture Topic Task] Document the risks found in tasks #107 and #108 as specified in class

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#109]
As mentioned in class, risks should be documented to support the evolution of the system. For each identified risks in tasks #107 and #108 document:

* The conditions/events for occurrence
* Estimated likelihood
* Possible consequences
* Estimated severity of each consequence
* Identified Countermeasures + risk reduction leverages 

To complete:
In a document add the details above for each risk recorded in tasks #107 and #108, then link the document to a comment in this tasks for further review.

**Comment by irsaris** [comment]
Hello, please suggest urgency and difficulty scores.

**Comment by BreannaGSegarra** [comment]
Fixed the name to properly include "[Lecture Topic Task]"!

**Comment by PinkSylvie** [comment]
@irsaris @Negroni1 @BreannaGSegarra I finally got the answers I was waiting from the QA so I was finally able to include the risks into the documentation. I also included a link to a document that provides an overview of the questionnaire and a link to it as well. Whenever you can could you review this new section, Section 4.6? Thank you!
