### ISSUE TITLE
Task: Enhancing User Experience

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#11]
Define in the documentation the persona/s and define a user story/narrative that convinces why this project would be useful (I bundled these together because for the person/s that handle the persona/s should probably also handle the user story as well).

**Comment by Mark-Anton** [comment]
Objective:

Primary Goal: Provide real-time visual feedback in the preview screen as the user makes edits.
Key Design Considerations:

User-Centric Feedback: Develop a system that offers meaningful visual cues to users during the editing process.
Ease of Use: Focus on creating a user-friendly environment that minimizes the learning curve.

Expected Outcomes:

A preview screen that offers accurate and real-time feedback, enhancing the overall user experience and making the editing process more intuitive and efficient.
