### ISSUE TITLE
Multiple languages for website

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#117]
in task #43, multiple language templates can also be extended to the website as well.

**Comment by irsaris** [comment]
Hello, is this a task you're still interested in doing?

**Comment by gabrielpadilla7** [comment]
Hello! Yes! I'm still interested in doing this task

**Comment by irsaris** [comment]
This is due in less than 2 hours.
