### ISSUE TITLE
[Lecture Topic Task] search for inconsistencies, conflicts, incompletenesses (cited from Domain Analysis and Concept Formation)

### ISSUE THREAD

**Issue by MrL9000** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#120]
Go over the already established domain description and make reccomendations on anything that should be cleared up.

**Comment by irsaris** [comment]
There are tasks for this that check in Domain, Interface and Machine Requirements. Where will you be looking for inconsistencies?

**Comment by MrL9000** [comment]
I was thinking of taking a look at the Domian specifically, basically just making sure that there aren't any loose ends or painpoints that we might have missed when defining the domain last milestone (would also be an excuse for me to take a good look at what's the overaching plan)

I suppose this task will be closed and I self assign the Domain one?

**Comment by MrL9000** [comment]
found it, closing as duplicate
