### ISSUE TITLE
(Preview resume, Task 3) Buttons for download and sharing (trigger download and sharing)

### ISSUE THREAD

**Issue by MrL9000** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#126]
Taken from the Milestone 2 google doc

**Comment by irsaris** [comment]
Hello, please suggest urgency and difficulty scores.

**Comment by MrL9000** [comment]
This one is also sort of halfway done because there's already a download button in the page, I could reinterpret this as updating the location of the download button and the implementation of a sharing functionality (which is likely the tougher task) so I'm taking this one

Irisaris wanted me to mention this in this task
