### ISSUE TITLE
Develop Keyboard Shortcuts for Faster Editing

### ISSUE THREAD

**Issue by Mark-Anton** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#127]
This task involves enhancing the user experience by implementing keyboard shortcuts for efficient and quick editing within the resume builder webpage. Users will be able to perform common actions such as adding sections, navigating between fields, and saving changes using designated keyboard combinations. This feature aims to streamline the editing process, providing users with a more fluid and intuitive interface, ultimately saving time and improving overall usability.

Difficulty: 3
Priority: 5

**Comment by irsaris** [comment]
Hello, will you still be working on this for this milestone?

**Comment by irsaris** [comment]
@Mark-Anton 

> Hello, will you still be working on this for this milestone?

**Comment by irsaris** [comment]
will this be worked on?
