### ISSUE TITLE
[Lecture Topic Task] Build a section for educational background entry

### ISSUE THREAD

**Issue by Mark-Anton** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#129]
Implementing a dedicated segment within the resume builder webpage that allows users to input and showcase their academic history. Current education level and school/universities the user had attained that education level from.

Difficulty: 2
Priority: 5

**Comment by Mark-Anton** [comment]
Education-Page branch is holds the user interface change made to the add education section of the website.
Here the user can view and generate prompts for personal information to be used in the resume that will be created.

![image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/42784582/bec3e063-4ec7-4f67-9acb-b8f9ebeaf206)
![image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/42784582/b6a7b10c-69b1-498e-b986-7b9373aedaaf)

**Comment by irsaris** [comment]
Hello, where is the PR for this?

**Comment by Mark-Anton** [comment]
UI and UX change and implementation [#202](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/pull/202)
