### ISSUE TITLE
Implement Education Page w/respected fields

### ISSUE THREAD

**Issue by Adrian-OCS** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#130]
The Education Page is a form that would take the user's information about academic achievements and will be displayed in the resume template of their choosing. The form should accept the following fields:

- School/Institute name (required)
- Degree/Certificate (required)
- Field of study (required)
- Year of Graduation (required)

**Comment by irsaris** [comment]
duplicate with #129
