### ISSUE TITLE
Implement Error handling and suggestions for each field (Education Page)

### ISSUE THREAD

**Issue by Adrian-OCS** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#131]
Error handling for inputs in Education Page fields such as "school/institute name", "degree/certificate", "field of study", "year of graduation".

**Comment by irsaris** [comment]
Hello, please suggest urgency and difficulty scores.

**Comment by irsaris** [comment]
Reminder: this is due before midnight today.

**Comment by irsaris** [comment]
I need a PR to close the issue
