### ISSUE TITLE
Add "Next" button in Education Page

### ISSUE THREAD

**Issue by Adrian-OCS** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#132]
Implement a button on the Education page that redirects the user to the next data entry page. Make sure that any data in the form is saved before redirecting the user.

**Comment by irsaris** [comment]
Reminder: this is due before midnight today.

**Comment by irsaris** [comment]
Please link a PR.

**Comment by irsaris** [comment]
trusting this will have a PR soon.

**Comment by irsaris** [comment]
So was this never done? @Adrian-OCS
