### ISSUE TITLE
[Lecture Topic Task] Stakeholder Documentation and Questionnaire Creation

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#135]
The project reviewed the requirements documentation and ensures:
- [x] that the requirements stakeholders are properly documented: who, why these, how related to the project…
- [x] that acquisition and the rest of the elicitation are separate
- [x] that at least one meaningful questionnaire for requirements acquisition is included

**Comment by PinkSylvie** [comment]
@irsaris @Negroni1 @BreannaGSegarra I verified the stakeholders in the stakeholder identification section and their descriptions seem to comply with what was asked for by the professor. I also took some parts of domain acquisition and separated them into domain elicitation. And I linked the rough sketch questions I used to interview stakeholders last milestone into the new domain elicitation section. Whenever you can could you review it?
