### ISSUE TITLE
[Lecture Topic Task] Analyzing Inconsistencies in Interface Requirements Analysis

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#139]
* The project reviewed their interface requirements analysis and ensured that they were analyzing inconsistencies for the specific types of clashes. If not, add them.

**Comment by JonathanDebug** [comment]
I wish to do this task.

**Comment by irsaris** [comment]
Hello, this is missing in the document (@Negroni1 for visibility).
