### ISSUE TITLE
Design the “Personal Information” data entry page

### ISSUE THREAD

**Issue by FrancesC8** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#14]
- Use either Figma or Canva to design the data entry page of the app.
- Design the page where the user will input their personal information that will be used in the resume. This includes information about the user’s name, contact information and summary.

Suggested points → Priority(P0) * Difficulty(Intermediate) = 5 * 3 = 15

**Comment by FrancesC8** [comment]
Finished the design for the "Personal Information"data page in [Figma](https://www.figma.com/file/U4MbLnfQo52wJupQ1hpB2Z/Personal-Details-Page?type=design&node-id=0%3A1&mode=design&t=zTV0Rw0cCVaCu2C2-1). @Negroni1 @irsaris

**Comment by Negroni1** [comment]
Well done 👍 👏 

![Image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/64982360/4befda11-3146-44df-8a44-d324e4e3b5a3)
