### ISSUE TITLE
[Lecture Topic Task] Identifying Weak Inconsistencies in Machine Requirements Analysis

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#143]
* The project reviewed their machine requirements analysis and ensured that they are including at least five weak inconsistencies together with the boundary condition that makes it inconsistent.

**Comment by FrancesC8** [comment]
Suggested points -> Priority(Medium) * Difficulty(Intermediate) = 4 * 4 = 16

**Comment by FrancesC8** [comment]
@irsaris @Negroni1 Este task esta completado, podran ver que la seccion de Machine Requirements algunos tienen weak inconsistencies. Ademas, pueden ver mi entrada en el changelog al final del [documento](https://docs.google.com/document/d/1MM1IqfHtAGnZ4WQDkrljNMihryT9Nigh0CCW0RDD8r8/edit?usp=sharing). 

Cierro el issue yo, o ustedes se encargan?
