### ISSUE TITLE
[Lecture Topic Task] Recognizing Competing Goals in Machine Requirements Analysis

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#144]
* The project reviewed their machine requirements analysis and ensured that they are identifying some competing goals together with examples of derived requirements. If not, add them.

**Comment by BreannaGSegarra** [comment]
Section completed: https://docs.google.com/document/d/1MM1IqfHtAGnZ4WQDkrljNMihryT9Nigh0CCW0RDD8r8/edit#heading=h.ab3kup4y2oph
