### ISSUE TITLE
[Lecture Topic Task] Risk Identification and Assessment using FMEA

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#147]
* The project shows at least three cases of risk identification using FMEA. It's recommended that they use scenarios to illustrate these risks. The project shows their assessment of some of all their risks with some justification/discussion.

**Comment by irsaris** [comment]
In which section is this in the documentation? The change log was not updated also.

**Comment by gabrielpadilla7** [comment]
> In which section is this in the documentation? The change log was not updated also.

Hello! I'm sorry I closed this so suddenly. I was told that this part was already done by the person who worked on the Risk Identification. It is in this part of the document: https://docs.google.com/document/d/1MM1IqfHtAGnZ4WQDkrljNMihryT9Nigh0CCW0RDD8r8/edit#heading=h.klkivhhu3auj

I have no idea who worked on it as they did not update the table

**Comment by irsaris** [comment]
There is a slight difference in what the two tasks are just make sure that your part does what is asked, no worries. I think the other task did more than they were supposed to but oh well. They did actually update the table, check again. If all seems to be fine you may close this again.

**Comment by gabrielpadilla7** [comment]
Before closing I will verify again and if everything looks set, I'll close the issue.

**Comment by gabrielpadilla7** [comment]
All seems to be fine. Closing issue
