### ISSUE TITLE
[Lecture Topic Task] Risk Identification with Guidewords and Assessment using FMEA

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#148]
* The project shows at least three cases where they used guidewords together with the risks that they generated using FMEA. It's recommended that they use scenarios to illustrate these risks. The project shows their assessment of some of all their risks with some justification/discussion.

**Comment by Elielh17** [comment]
The Risk Identification with Guidewords and Assessment using FMEA have been implemented as the 3.3 section of the documentation.

Section 3.3: https://docs.google.com/document/d/1MM1IqfHtAGnZ4WQDkrljNMihryT9Nigh0CCW0RDD8r8/edit#heading=h.klkivhhu3auj

The following was added:

3.3 Risk Identification and Assessment in UPResuMe Project
In the development of the UPResuMe project, identifying and managing potential risks is pivotal to ensuring the robustness and success of our automated resume builder. By systematically identifying risks through guidewords and assessing them using Failure Mode and Effects Analysis (FMEA), we enhance our project's resilience against unforeseen challenges.

Guideword Utilization
Guidewords have been instrumental in initiating our risk identification process. This method prompted our team to consider deviations in various project aspects, such as software functionality, user data security, and deployment infrastructure.
Application of FMEA
Following the initial identification, FMEA allowed us to delve deeper into each risk, evaluating them based on their severity, likelihood of occurrence, and detectability. This assessment informed our prioritization of risks and the formulation of targeted mitigation strategies.
Risk Cases Illustration
Scenario: Template Gallery Functionality
Identified Risks: Inadequate template variety, slow template loading times.
FMEA Assessment: Severity (4), Occurrence (2), Detection (3). Mitigation included optimizing image sizes and increasing server resources.
Scenario: User Data Security
Identified Risks: Potential data breaches, unauthorized access to user resumes.
FMEA Assessment: Severity (5), Occurrence (3), Detection (2). Strategies involved implementing enhanced encryption and regular security audits.
Scenario: Real-Time Resume Editing Feature
Identified Risks: Lag in real-time updates, user edits not saving correctly.
FMEA Assessment: Severity (3), Occurrence (4), Detection (3). Solutions included code optimization and introducing session backups.
Discussion and Justification
Our rigorous application of guidewords and FMEA has underscored the critical nature of proactive risk management in the UPResuMe project. By identifying and assessing potential risks early, we have been able to implement effective mitigation strategies, ensuring the project remains on track and delivers a high-quality product to our users.
The integration of risk identification and assessment into the UPResuMe project's management processes exemplifies our commitment to quality and reliability. Through guided brainstorming and detailed FMEA, we have laid a solid foundation for addressing potential challenges, safeguarding our project's success and our users' satisfaction.
