### ISSUE TITLE
[Lecture Topic Task] Prioritizing Requirements using AHP based on Team Input

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#150]
* The project shows evaluation criteria and how they arrived at these using each team member's input. They use AHP for both of this. For example, using the tool <https://github.com/gluc/ahp> in R by following the "vacation" example there.

**Comment by GaddPetrivoki** [comment]
Started getting team members inputs on what criterions we should use. Members were randomly selected from each team. Both managers were also specifically asked as their input has some more importance than team members.

**Comment by GaddPetrivoki** [comment]
Criterions that were chosen based on team member input and managers were.

1. Streamlining Resume Creation
2. Quality of Resume
3. User Retention
4. Functionality of website

To figure out the criterions weights team input has been asked through a google form.

**Comment by irsaris** [comment]
Thanks for notifying this, remember that all that goes in the Milestone documentation :]

**Comment by irsaris** [comment]
Hello, this is missing in the document (@Negroni1 for visibility).
