### ISSUE TITLE
[Lecture Topic Task] "Discussion of Satisfiability and Feasibility in Domain Requirements"

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#151]
* The project shows an example of domain requirements where they discuss satisfiability and feasibility.

**Comment by gabrielpadilla7** [comment]
Added the Satisfiability and feasibility in the domain requirements. If there's nothing to edit or change, issue can be closed. Just let me know!

**Comment by irsaris** [comment]
Hello, I'm not sure where it is in the document, remember the guidelines and update the table.

**Comment by gabrielpadilla7** [comment]
Hello! I did modify the table, and the satisfiability and feasibility has been added to the domain requirements, they're highlighted in green as per the guidelines.

**Comment by irsaris** [comment]
awesome!
