### ISSUE TITLE
[Lecture Topic Task] Discussion of Satisfiability and Feasibility in Interface Requirements

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#153]
* The project shows an example of interface requirements where they discuss satisfiability and feasibility.

**Comment by Keiven-Soto** [comment]
I can work on this

**Comment by irsaris** [comment]
Hello, this is missing in the document (@Negroni1 for visibility).
