### ISSUE TITLE
[Lecture Topic Task] Discussion of Satisfiability and Feasibility in Machine Requirements

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#154]
* The project shows an example of machine requirements where they discuss satisfiability and feasibility.

**Comment by FrancesC8** [comment]
Suggested points -> Priority(Medium) * Difficulty(Intermediate) = 4 * 4 = 16

**Comment by FrancesC8** [comment]
@irsaris @Negroni1 Este task esta completado, podran ver que la seccion de Machine Requirements algunos tienen argumentos sobre Satisfiability and Feasibility. Ademas, pueden ver mi entrada en el changelog al final del [documento](https://docs.google.com/document/d/1MM1IqfHtAGnZ4WQDkrljNMihryT9Nigh0CCW0RDD8r8/edit?usp=sharing). 

Cierro el issue yo, o ustedes se encargan?
