### ISSUE TITLE
Implement a preview feature

### ISSUE THREAD

**Issue by Keiven-Soto** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#156]
Big Preview (picture) of template

**Comment by irsaris** [comment]
This is believed that’s only previewing the template itself, not the resume. The other task mentioned does the other one.

**Comment by Keiven-Soto** [comment]
![Image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/78508728/13f682ed-fdc3-405b-8927-4943262d9076)

**Comment by Keiven-Soto** [comment]
Task has been completed and it meets acceptance criteria

**Comment by irsaris** [comment]
#207
