### ISSUE TITLE
Being able to log in

### ISSUE THREAD

**Issue by BryanDVG** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#157]
Create a page for the templates and add it into the Nav Bar "Templates".

**Comment by Janiel777** [comment]
Once the end point with which the email and a password are requested from the front to validate it with the information in the database has been implemented, now we must use that endpoint in the front. In addition, it is necessary to implement that the user's information is persistent even when the page is refreshed. That is why you have to use the token that the already implemented endpoint returns as a response to the front to save it in the localStorage and create a function in the user ctontext that is executed every time the page is refreshed. What this method does is that it takes the token saved in the localStorage and searches for the user in the database associated with it, creating a new endpoint in the back end that allows the user to be obtained through this token. This fetch is done in the userContext and it updates the user information depending on the result of the fetch. Additionally, you can very easily implement a close section button that simply deletes the token from the local storage and refreshes the page. This button may be temporarily in the navbar.

**Comment by Janiel777** [comment]
I understand that it can be given a score of: Difficulty: 5 Priority: 4
