### ISSUE TITLE
Template Button Functionality

### ISSUE THREAD

**Issue by BryanDVG** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#159]
When the user selects the template in the gallery of templates, a pop-up appears with the corresponding template and the user is redirected to enter his personal info so that the resume can be created.

**Comment by irsaris** [comment]
Hello, please suggest urgency and difficulty scores.

**Comment by Keiven-Soto** [comment]
This feature has been implemented. Banner appears once the user select the template. All acceptance criteria have been met.
