### ISSUE TITLE
Come up with the website general apperance and design document.

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#16]
We need to make a general document with basic style rules for the website. This includes:

- Colors that'll be used
- Logos
- Website Layout ( on mobile and on PC )

Deliverables for this would come in some kind of design document pdf that addresses how we expect the website to look and what the general user experience is to be.

**Comment by GaddPetrivoki** [comment]
# Description 

We need to make a general document with basic style rules for the website. This includes:
- Colors that'll be used
- Logos
- Website Layout ( on mobile and on PC )

Deliverables for this would come in some kind of design document pdf that addresses how we expect the website to look and what the general user experience is to be.

**Comment by GaddPetrivoki** [comment]
@irsaris @Negroni1 @FrancesC8 

Isn't #13 and this duplicates? How are we divvying this up?

**Comment by irsaris** [comment]
@GaddPetrivoki 
It's two different tasks, this one is for the homepage design, issue #13 is for login and sign up.
Hope that clears things up.

**Comment by GaddPetrivoki** [comment]
> @GaddPetrivoki It's two different tasks, this one is for the homepage design, issue #13 is for login and sign up. Hope that clears things up.

My original intentions with this task was a style guide for the website. If it's just the design for the home page then that'll be pretty straightforward. Does the home page include both the non-user view and user view?

**Comment by Negroni1** [comment]
If you'd like to do the general style guide for the website, please go ahead and do so, I think it is a good idea. Just don't go into much detail (as those are other tasks). What do you mean by non-user view?

**Comment by GaddPetrivoki** [comment]
Playing with layout ideas for home page and main editor.
![Style Guide Draft 2024-02-15 10 15 06 excalidraw](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/13458383/841bdf11-dcfd-4e77-b8a8-bb2eac97ff89)

**Comment by GaddPetrivoki** [comment]
> If you'd like to do the general style guide for the website, please go ahead and do so, I think it is a good idea. Just don't go into much detail (as those are other tasks). What do you mean by non-user view?

Non-user view refers to people who aren't registered on the platform. Wasn't quite sure what word to refer to them.

**Comment by Keiven-Soto** [comment]
This issue has been completed and revised

**Comment by GaddPetrivoki** [comment]
[main.pdf](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/files/14368108/main.pdf)
