### ISSUE TITLE
Create the demo run through for demo day

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#161]
Demo must include a voice over of the run through

**Comment by irsaris** [comment]
Hello, please suggest urgency and difficulty scores.

**Comment by gabrielpadilla7** [comment]
Priority: 2
Difficulty: 3

**Comment by irsaris** [comment]
Will be closed with the promise of it being completed before the deadline next week. Please also include a voiceover explaining what the viewer is seeing in the demo vid.
