### ISSUE TITLE
Click on template (sends the user to template selection)

### ISSUE THREAD

**Issue by Elielh17** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#166]
Create a button or give functionality to an existent one that when clicked takes the user to the template selection page.

Urgency: 4
Difficulty: 2

**Comment by irsaris** [comment]
duplicate of #159

**Comment by Elielh17** [comment]
Implemented the functionality for the button of templates in the home page. When the templates page branch is merged it should work.

commit: https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/commit/b031ec36fd8d5908d4155af036e468574458ecab
