### ISSUE TITLE
Implement Experience Page

### ISSUE THREAD

**Issue by BreannaGSegarra** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#168]
Implement the experience page, which has the following specifications:
1. Have page display title tab, templates tab, and resume tab on the top.
2. Allow user to add experience entry to the experience section, including job title, company/organization, start date, end date, responsibilities, and achievements.

Recommended Priority: 4
Recommended Difficulty: 4

**Comment by JonathanDebug** [comment]
Hi! can i take this task?

**Comment by JonathanDebug** [comment]
Task has been completed, branch pushed.
