### ISSUE TITLE
Create a prototype template capable of being mutated into other templates.

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#17]
With the templates we're gonna have to setup some basic functionality that will be shared between all templates.

- Use a template
- Edit a template
- Delete a template
- Create a template
- Change templates

These base functions seem to be the most obvious, but I'm not sure how far we will expand on the templates. Further discussion should be had as to what we're expecting.

> Should we handle templates as objects?
> Are we gonna allow users to mess around with templates?
> Should you just be able to change between templates?

Further discussion is necessary to delineate deliverables.

**Comment by GaddPetrivoki** [comment]
# Description

With the templates we're gonna have to setup some basic functionality that will be shared between all templates.
- Use a template
- **Edit a template**
- **Delete a template**
- **Create a template**
- **Change templates**

These base functions seem to be the most obvious, but I'm not sure how far we will expand on the templates. Further discussion should be had as to what we're expecting.

**Comment by GaddPetrivoki** [comment]
I think it's clear the best route for template creation is to just use HTML files. There's no need to over complicate stuff creating our own in-house built solution when some HTML and CSS can handle all of our cases. We can implement basic custom tags and just run a js script to fill in most parts. The rest can be easily edited.

**Comment by GaddPetrivoki** [comment]
Templates can just consist of an HTML file and a CSS file. Something like in the image should be more than fine. It'll give us the flexibility to create more templates easily and fast and possibly in the future allowing users to create their own templates. 

![Drawing 2024-02-22 16 31 28 excalidraw](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/13458383/b6923348-d041-4d20-bf85-9720d2e08ca5)

**Comment by Keiven-Soto** [comment]
Acceptance criteria met and reviewed
