### ISSUE TITLE
Implement Additional Information Page

### ISSUE THREAD

**Issue by BreannaGSegarra** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#174]
Implement the additional information page, which has the following specifications:
1. Have page display title tab, templates tab, and resume tab on the top.
2. Allow user to add additional information entry to the additional information section, including projects, certifications, awards, and honors.

Recommended Priority: 4
Recommended Difficulty: 4

**Comment by Mark-Anton** [comment]
Additional information model and prompt once selected to add information:
![image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/42784582/6cbf1d16-0d3d-43b2-ba96-deba1dd9bb99)

Pull Request: Additional Information Modal #204
