### ISSUE TITLE
Task 1.2: Implement JUnit test

### ISSUE THREAD

**Issue by JuanJRivera** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#176]
Apply JUnit's the function for the Save Resume Information + template unto the user account.

**Comment by irsaris** [comment]
Can you specify for what feature or where these would be implemented towards? Theres already one for the preview resume feature

**Comment by JuanJRivera** [comment]
updated.

**Comment by irsaris** [comment]
Update on this?
