### ISSUE TITLE
Implement Error Handling and Suggestions for Experience Page

### ISSUE THREAD

**Issue by BreannaGSegarra** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#178]
Implement error handling and suggestions for experience page, which has the following specifications:
1. Implement logic to handle common errors (missing fields, impossible data, and other edge cases).
2. Provide (autofill) suggestions for each field.

Recommended Priority: 3
Recommended Difficulty: 4

**Comment by irsaris** [comment]
Reminder: this is due before midnight today.

**Comment by irsaris** [comment]
#208
