### ISSUE TITLE
Implement "Next" Button for Skills Page

### ISSUE THREAD

**Issue by BreannaGSegarra** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#183]
Implement the next button for the skills page, which has the following specifications:
1. Display "Next" button whenever user is done adding an entry to the skills section.
2. Have "Next" button take user to the additional information page.

Recommended Priority: 3
Recommended Difficulty: 4

**Comment by JorgeC08** [comment]
Already added the skills section, waiting for pull approval.

**Comment by irsaris** [comment]
link the pull request

**Comment by JorgeC08** [comment]
> link the pull request or was it already merged?

I thought that I linked the pull request but I linked the same Issue by mistake. My bad.
