### ISSUE TITLE
Allow basic editing of templates

### ISSUE THREAD

**Issue by GaddPetrivoki** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#185]
Be able to edit basic info of a template. 
- Name
- Skills

**Comment by irsaris** [comment]
Can you be more specific about what this task is?

**Comment by GaddPetrivoki** [comment]
@irsaris 

This tasks would be part of a series of issues allowing users to fully customize templates and publish them to the website. Starting off would be allowing them to do basic edits of info on a template such as the adding of Names and skills. In future milestones we would allow users to edit and create new sections, add images, customize colors, and font of the template. This would allow users to create more templates to expand their gallery. At the moment I understand we only have 3 hard coded templates that don't offer much in the way of customization so I think a good start would be to allow users to be able to change basic texts parts of a document.

**Comment by irsaris** [comment]
suggest difficulty and urgency

**Comment by GaddPetrivoki** [comment]
> suggest difficulty and urgency

Dificulty: 5
Urgency: 3 or 4?

**Comment by GaddPetrivoki** [comment]
Branch merged into templates. Issue finished.

**Comment by irsaris** [comment]
Link the pull request.
