### ISSUE TITLE
[Lecture Topic Task] Create TLA+ model

### ISSUE THREAD

**Issue by JonathanDebug** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#187]
"The assignment that replaces the two meetings: use TLA+ for requirements validation. On https://lamport.azurewebsites.net/tla/tla.html you can find lots of material on TLA+ including the book Specifying Systems and on YouTube there are lots of tutorials. Then use your requirements and specify a model of a system that satisfies (at least some relevant) requirements, formulate properties, and model check these properties."

**Comment by JonathanDebug** [comment]
Hello, please close this issue since i has already been made.

**Comment by irsaris** [comment]
This is due in less than 2 hours.
