### ISSUE TITLE
Set up Tailwind CSS and shadcn/ui

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#189]
Set up Tailwind CSS and shadcn/ui to facilitate the styling process for the website

**Comment by gabrielpadilla7** [comment]
@irsaris I've made this issue to be able to set this up to facilitate the styling process for everyone. Once done, I'll do a PR and update the readme

**Comment by gabrielpadilla7** [comment]
It is proving to be a little more difficult than anticipated thanks to the project being in JS and not TypeScript, as well as a few other factors (missing files, etc)

**Comment by irsaris** [comment]
Will you still be doing it? Is there a scoring you'd like to update?

**Comment by gabrielpadilla7** [comment]
> Will you still be doing it? Is there a scoring you'd like to update?

Right now I'm not sure about the scoring update. I will not be doing it with these, however I'm currently researching for other ones to see if they can be implemented for our code. It's really a bummer that this one doesn't work great with the already implemented code

**Comment by irsaris** [comment]
Ah I see, well keep me posted then. When you finalize your decision with suggested scoring, I'll move it to the official board.

**Comment by gabrielpadilla7** [comment]
> Ah I see, well keep me posted then. When you finalize your decision with suggested scoring, I'll move it to the official board.

Alright! Once I've found a suitable replacement, I'll tag you and modify this issue

**Comment by irsaris** [comment]
@gabrielpadilla7 will this be implemented, if not I'll remove the task from the board

**Comment by gabrielpadilla7** [comment]
This will unfortunately not be implemented
