### ISSUE TITLE
Pass user information to resume

### ISSUE THREAD

**Issue by Janiel777** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#190]
# This is a basic description. Later it will improve.
All data/information entered shall appear on the resume appropriately arrange (based on template placeholders)

**Comment by irsaris** [comment]
@Janiel777 will you be doing this task?

**Comment by Janiel777** [comment]
Estuve investigando de que manera se podria implementar esto y es bastante retador. Por lo que pude encontrar, tengo dos posibles maneras de implementar esto.

1. Utilizando pdfkit, los templates serian generados por codigo. Es decir, que cada pdf tendria un codigo que genera un template en espesifico. Esto implica volverse bastante diestro con las herramientas que brinda pdfkit y es basicamente como crear un resume en word solo que en vez de tener una interfaz amigable, el resume se crearia a travez de codigo (lo cual es bastante retador). Despues de esto, se tendria que localizar las posiciones en la que se supone que iria la informacion de la persona. Teniendo ya localizado las posiciones, ya solo es cuestion de recibir como parametros esos valores y que remplacen valores provisionales.
2. Utilizar pdf-lib. Esta es otra libreria que permite crear desde cero pero tambien permite trabajar con un pdf ya creado. Lo que encontre util de esta libreria es que si el pdf contiene forms fields, este te permite muy facil acceder y escribir en ellos. Es decir que, si se crea un template, se pasa a pdf, se crean forms fields para cada informacion del usuario en sus respectivas ubicaciones del template, ya solo es cuestion de acceder y escribir en ellas desde el codigo. Ahora, cual es el problema con esto? Lo que pasa es que no encontre una manera de hacer que los forms no se vean en el documento. Los forms siempre suelen estar como un recuadro de texto y suelen tener el fondo de ese recuadro de un color mas oscuro al del fondo. Osea que visualmente para un resume, tener cada campo de texto con un recuadro no es muy bonito y presentable que digamos. 

Tienen que haber mas maneras de como implementar esto. Asi que pueden intentar buscar mas soluciones pero no creo que ninguna de ellas sea sencilla. Yo ya tengo todos mis puntos para este milestone y creo haber aportado algo en el desarrollo de este issue asi que si nadie se atreve a tomar este reto para este milestone, que se quede entonces para el milestone 3 con la posibilidad de ser un issue que se comparta entre mas de una o dos personas.
