### ISSUE TITLE
Template Selecting Features

### ISSUE THREAD

**Issue by GaddPetrivoki** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#194]
Implement a functionality that allows the user to select a template based out of the selections available
Urgency: 5
Dificulty: 4

Acceptance Criteria:
Templates appear on the left side of the page
Changing views of the templates works correctly

**Comment by irsaris** [comment]
@GaddPetrivoki will you be doing this task?

**Comment by irsaris** [comment]
Suggest difficulty and urgency (also we only get notifications for a reply so we didnt see the emoji)

**Comment by GaddPetrivoki** [comment]
Ya esta implementado en el branch de templates. Se puede escoger entre dos templates actualmente y se puede expandir facilmente a mas templates. Hecho junto a @BryanDVG
