### ISSUE TITLE
Validate the template selection function

### ISSUE THREAD

**Issue by GaddPetrivoki** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#195]
Urgency: 5
Dificulty; 4

**Comment by irsaris** [comment]
Provide an accurate description for this task.

**Comment by GaddPetrivoki** [comment]
Ensure that template selection function works properly. Previously the template selection function was hardcoded and had issues changing from one template to another.

**Comment by GaddPetrivoki** [comment]
Modified how templates are handled. They're now kept in an array separate from the conditional. The bug involving going from one template to another should no longer be happening.

**Comment by irsaris** [comment]
Link the pull request
