### ISSUE TITLE
Fix bug with preview page

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#196]
The preview page styling and background is not dynamic with the window size. This issue fixes the bugs within the styling of the preview page. 

suggested difficulty: 4
Urgency: 3

**Comment by gabrielpadilla7** [comment]
@irsaris I've found this bug, I have a way to fix it which is why I made it

**Comment by irsaris** [comment]
Ok go ahead

**Comment by Janiel777** [comment]
Gracias por arreglar ese problema. Aunque si tenía pensado cambiar yo el estilo que le puse al preview page para que se pareciera al Landing page ya que este quedó más bonito y arreglar ese problema del preview, trate de hacerlo pero no me salió y lo iba a intentar de nuevo más después. Pero me parece cool que hallas tomado la iniciativa de arreglarlo tu mismo. Gracias de nuevo, a mí no se me da muy bien bregar con código CSS.

**Comment by gabrielpadilla7** [comment]
> Gracias por arreglar ese problema. Aunque si tenía pensado cambiar yo el estilo que le puse al preview page para que se pareciera al Landing page ya que este quedó más bonito y arreglar ese problema del preview, trate de hacerlo pero no me salió y lo iba a intentar de nuevo más después. Pero me parece cool que hallas tomado la iniciativa de arreglarlo tu mismo. Gracias de nuevo, a mí no se me da muy bien bregar con código CSS.

Of course! Aqui a la orden. Cualquier cosa que necesiten de CSS yo los puedo ayudar para mantener una estructura uniforme a traves del programa
