### ISSUE TITLE
User data storage

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#20]
Create a database where all of the user data will be stored in. This must include all of the user data that the user input on the form, as well as the login data (even if some of the user input is blank, such as in the case of optional inputs in the form)

Difficulty: (4)
Priority: P0

**Comment by JorgeC08** [comment]
All the tables have been created and added to the server in ElephantSQL. All the code for the table can be found on db.sql on the repository.
