### ISSUE TITLE
[Lecture Topic Task] (Doc Feedback) Fix apply traceability 

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#215]
"You suggest some straightforward ideas for traceability on your project, but I do not see any of these actually applied."

**Comment by JonathanDebug** [comment]
I have applied the majority of the traceability. Here is what i have not implemented: 

"Establish links between requirements and the tests that validate them. Each requirement should be associated with one or more tests that verify its functionality or behavior.
Document the validation activities (such as user testing, code reviews, or system demonstrations) that validate each requirement. This provides insight into the verification process and ensures that requirements are adequately tested.
Monitor the current state of test coverage for each requirement, including the number of tests related to the requirement and their pass/fail status. This helps assess the completeness and quality of the testing effort."

The only one that I could do is the first one but I dont see any tests that have been documented yet. The other ones are other sections that when more tests are done and documented, they should be covered. Should i wait for more tests to be documented? If not please revise and close. @irsaris

**Comment by irsaris** [comment]
Where have you applied the tracebility? I dont see a PR

**Comment by JonathanDebug** [comment]
Added traceability to the points mentioned.
