### ISSUE TITLE
[Lecture Topic Task] (Doc Feedback) Fix Risk section

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#217]
"For your risk assessment you first want to see clearly what is at risk: legal problems or loss of user base are long term subsequent effects, more immediately we would have to assess what an adversary could gain. Here we have a lot: personal information, employment history, education history, address, contact information,... An encryption scheme would not avert e.g. an impersonation, i.e. an attacker getting a user's username and password: communication would be encrypted, but to the wrong recipient. Help of further encryption is still a bit vague. Countermeasures could be: storing all information on the system using a user-defined encryption key and only decrypting it for the session in which the user uses that information. Storing the generated PDFs with the same encryption or not storing them at all (if they can be recreated easily). An alternative would be to only store data on the user's device. This has severe disadvantages since the user can no longer easily switch to another device. That functionality could then still be provided, but would require extra effort."

"The project does not shows application of risk reduction tactics."

**Comment by PinkSylvie** [comment]
@irsaris @Negroni1 @BreannaGSegarra I went over the risk section in the documentation, added and fixed them according to the professor's feedback and had them looked over by the professor as well. Whenever you can could look over the additions and eliminations I did in section 4.5 to close the task?
