### ISSUE TITLE
[Lecture Topic Task] (Doc Feedback) Fix Weak Inconsistencies 

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#218]
"A weak inconsistency occurs what we have two statements that are not immediately in conflict, but under a boundary condition become conflicting. For example, if we have a stakeholder saying "the system must provide means for editing their resumes" and we have another stakeholder saying "the system must provide a record of all the resumes that were used/sent out". A boundary condition would be a user wanting to edit a resume that was already sent out: the first requirement requires that the system must provide means for the user to edit the resume, the second requirement requires that the resume must be kept as record, since it was sent out. Then we can think about how the resolve it, for example by creating a new version those resumes that were already sent out but that a user now wants to edit. The (weak) inconsistency exploration is not complete if there's not also the consideration of how to resolve the inconsistency.

"There is a lack of clarity on what it means for an interface to be intuitive and user-friendly" this is not a weak inconsistency (see above). Review all the weak inconsistencies along the example above."

**Comment by JonathanDebug** [comment]
I have added resolutions and boundary condition to all the weak inconsistencies, marked the changes in green. Please check when possible.

**Comment by irsaris** [comment]
@BreannaGSegarra could you check this? i'm not sure if what was done is what the professor asked for and i want to make sure

**Comment by JonathanDebug** [comment]
@irsaris
