### ISSUE TITLE
Design basic templates 

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#22]
Design templates for the user to select and use. Templates can also be suggested based off the amount of data entered in the form.

Difficulty: (2)
Priority: P1

**Comment by JConcepcion01** [comment]
![Image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/99218117/ebf4d8d8-f90b-4991-8488-493e2120449f)
![Image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/99218117/d2484b45-9cdc-49e8-ae30-0912cb6d39e0)
![Image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/99218117/3c85d808-4e9a-425b-bd69-b645a1ed5175)
![Image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/99218117/87ae41ee-06e7-4183-a76b-ef9ca932a4d8)
![Image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/99218117/c396110b-ebe1-4c98-bb5d-1babc97dcdbf)
