### ISSUE TITLE
[Lecture Topic Task] Structures diagram

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#225]
"Enhance and complement the documentation with structures (entity-relationship diagrams) diagrams."

**Comment by Chosen-Juan1** [comment]
<img width="902" alt="Screenshot 2024-04-26 at 4 07 14 PM" src="https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/101728824/29cef185-5a5e-43ac-ac81-5da8accf377f">
Improved my previous designed of the ER. Professor recommended that i keep it light and that I should put the details in the description of the ER.

**Comment by Chosen-Juan1** [comment]
@irsaris What do you think?

**Comment by irsaris** [comment]
Yeah, if you incorporated the professor's feedback and all then it should be good to go, remember to update it in the documentation.
