### ISSUE TITLE
[Lecture Topic Task] Activities and data diagram

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#226]
"Enhance and complement the documentation with activities and data (SADT diagrams) diagram."

**Comment by Chosen-Juan1** [comment]
The professor has stated that it is a good design, I shall add it when I'm done with my other tasks and close this one.

**Comment by irsaris** [comment]
Ok notify when it is in the documentation

**Comment by Chosen-Juan1** [comment]
Where specifically?

**Comment by irsaris** [comment]
wherever you think fits best, could be in the implementation section or somewhere else

**Comment by Chosen-Juan1** [comment]
Added it in the implementation section as figure 5, this can be closed now.
