### ISSUE TITLE
[Lecture Topic Task] Information flows diagram

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#227]
"Enhance and complement the documentation with information flows (dataflow diagrams) diagram."

**Comment by FrancesC8** [comment]
Suggested points -> Priority(Medium) * Difficulty(Intermediate) = 4 * 4 = 16

**Comment by irsaris** [comment]
This is due in less than 2 hours.

**Comment by FrancesC8** [comment]
@irsaris I added the data flow diagram in the 2.3 Implementation section of the documentation. The diagram is titled "Information flow diagram for creating/editing resume operation".
