### ISSUE TITLE
[Lecture Topic Task] System operations diagram

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#228]
"Enhance and complement the documentation with system operations (use case diagrams) diagram."

**Comment by Negroni1** [comment]
![Image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/64982360/a16a990e-bb3e-465e-85e3-bb3cea0ab2c2)
