### ISSUE TITLE
[Lecture Topic Task] Interaction scenarios diagram

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#229]
"Enhance and complement the documentation with interaction scenarios (event trace diagrams) diagram."

**Comment by Negroni1** [comment]
![Image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/64982360/a7bc5cff-1c08-45d1-a73f-e80d2d193fc7)
