### ISSUE TITLE
[Lecture Topic Task] Fill out the section "4.2 personas" found in "[UPResuMe] Milestone 1"

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#23]
Define in the documentation the persona/s to use human nature's ability to quickly recognize faces to facilitate the process of developing the project (must be a person that one can reasonably believe could exist

**Comment by Chosen-Juan1** [comment]
Changed the title of the task, as we had redundant sections in the documentation.

**Comment by Chosen-Juan1** [comment]
Added 3 personas to section 3 and provided an assessment regarding their importance to the project and how much should their perspectives be considered.

**Comment by irsaris** [comment]
@Chosen-Juan1 could you add photos of the personas?

**Comment by Chosen-Juan1** [comment]
Sure, I think I can get some stock fotos and add them to the documtation.

**Comment by Chosen-Juan1** [comment]
Added photos for each persona. At the end of the section, added page where i obtained them.
