### ISSUE TITLE
[Lecture Topic Task] System behaviors diagram

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#230]
"Enhance and complement the documentation with system behaviors (state machine diagrams) diagram."

**Comment by FrancesC8** [comment]
Suggested points -> Priority(Medium) * Difficulty(Intermediate) = 4 * 4 = 16

**Comment by irsaris** [comment]
This is due in less than 2 hours.

**Comment by FrancesC8** [comment]
@irsaris this is done, you can find it under section 2.1 Domain Description - Behaviors.
