### ISSUE TITLE
[Lecture Topic Task] Requirements inspection using defect-driven checklist

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#231]
Description: Add to the analytical section. Include who the inspectors are, the (substantial) question catalog the inspectors used, the items considered, the finding of the inspectors.

**Comment by irsaris** [comment]
Make sure to write this in the 3.2.1.2 Defect Driven Inspection section

**Comment by BreannaGSegarra** [comment]
Done: https://docs.google.com/document/d/1HQ6cJZ1J2_AvUJUogcupNSgzu-ciTciXjRBz6GURfL0/edit#heading=h.i0ipilda6pdn
