### ISSUE TITLE
Implement edit Personal Information page

### ISSUE THREAD

**Issue by FrancesC8** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#235]
The personal information page, currently it only allows the user to create/add personal information to a resume. This task is to add the necessary logic that enables the user to edit a resume's personal information section. Meeting with the the project's requirements that an user should be able to edit a resume.

Suggested points -> Priority(Medium) * Difficulty(Hard) = 4 * 6 = 24

**Comment by irsaris** [comment]
This is due in less than 2 hours.
