### ISSUE TITLE
Change User table to only contain user/account related information

### ISSUE THREAD

**Issue by FrancesC8** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#236]
The user table contains personal information that will be added to resumes. This task is to delete all personal information from the User table in the database that isn't related to the user/account. Any personal information related to the resume should go to the personal_information table in the database.

This includes changing all api endpoints and queries related to user and front end logic related to user. 

Note: it is suggested to breakdown this task more.

**Comment by irsaris** [comment]
@JeremySanchez1 suggest scoring
