### ISSUE TITLE
Create resume table 

### ISSUE THREAD

**Issue by FrancesC8** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#237]
Create a resume table in the database to enable the user to have multiple resumes and the information can be related to each individual resume. The resume-related information tables (personal_info, work_experience, etc.) should be pointing to the resume table, and the resume table pointing to the user. Additionally, this enables the user to edit the information on their resume easily.

**Comment by irsaris** [comment]
@JeremySanchez1 suggest scoring
