### ISSUE TITLE
Investigate Inspectors for Domain-Model Quality Inspection

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#238]
This task is connected to task #234

Investigate what qualities would be needed for an inspector to be able to inspect the domain model's quality, what questions would they ask to be able to do so and what items would they consider to inspect

To complete: 
Link in the comments of this task a document with the result of the investigations regarding Inspectors for the Domain-Model Quality Inspection

Suggested Scoring:
Urgency 5 x Difficulty 2

**Comment by PinkSylvie** [comment]
@irsaris @Negroni1 @BreannaGSegarra - Linking it [here](https://docs.google.com/document/d/1E_ePxopFXOyOUqVsBaB8M48W5F-NucJpeXK1VlA5BhU/edit) but I already added the results in the documentation in its own section, section 3.2.1.1.2  Quality Driven Inspectors. . Whenever you can could look over the additions I did and close this task?

**Comment by irsaris** [comment]
The section after that one 3.2.1.2 Defect Driven Inspection is blank, will that be filled in?

**Comment by PinkSylvie** [comment]
Weren't tasks created for the defect driven checklist, similar to mine?

**Comment by irsaris** [comment]
Yeah, youre right, forgot about that for a sec
