### ISSUE TITLE
[Lecture Topic Task] The generation of an Impact Matrix for the project

### ISSUE THREAD

**Issue by MrL9000** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#241]
Generate an Impact Matrix to have a systematic way to asses the various risks the project may face once a minimum viable product is finished to be able to prioritize the risks that are most urgent and likely or frequent.

**Comment by GaddPetrivoki** [comment]
Anyone already doing this? If not I can give it a shot.

**Comment by MrL9000** [comment]
I made this task for those that require lecture topic tasks, and in the top right of the screen it says "Assignees No one", so, yea, knock yourself out

**Comment by MrL9000** [comment]
I think I can assign it to you, hold on

**Comment by irsaris** [comment]
@GaddPetrivoki suggest scoring

**Comment by GaddPetrivoki** [comment]
![Drawing 2024-04-18 21 17 38 excalidraw](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/13458383/6539781b-dd79-40d3-ba1b-2ca4b87cafa5)

**Comment by Keiven-Soto** [comment]
Task completed

**Comment by irsaris** [comment]
@GaddPetrivoki make sure to add it into the documentation
