### ISSUE TITLE
[Lecture Topic Task] Update and/or Add Diagrams to improve Specification & Documentation

### ISSUE THREAD

**Issue by MrL9000** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#242]
Update or add documentation diagrams to follow the structure and guidelines in Chapter 4, Requirements Specification & Documentation

**Comment by irsaris** [comment]
@Keiven-Soto suggest scoring

**Comment by Keiven-Soto** [comment]
Urgency: 5
Difficulty: 4
