### ISSUE TITLE
UI/UX for /resume/datainput page

### ISSUE THREAD

**Issue by Mark-Anton** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#243]
Implement a new user interface and user experience that is consistent with the pop ups on the data input page
Priority: 4
Difficulty: 5

**Comment by Mark-Anton** [comment]
![image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/42784582/45489fd5-f6e0-43bb-b5be-1be2dbf3f1bb)

I change the background color from grey to a dark green like the main page and contained each textfield into a box with a lighter green coloration instead of the monotone grey it previously had

**Comment by irsaris** [comment]
where is the PR?

**Comment by Mark-Anton** [comment]
https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/pull/290
