### ISSUE TITLE
Consistent UI/UX for pop ups etc

### ISSUE THREAD

**Issue by Mark-Anton** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#244]
Change the user interface and user interface for all pop ups.

Difficulty: 2
Priority: 5

**Comment by irsaris** [comment]
link the PR to the issue

**Comment by Mark-Anton** [comment]
https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/pull/290
