### ISSUE TITLE
Stylized navigation bar

### ISSUE THREAD

**Issue by Mark-Anton** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#245]
Change user interface and user experience for the navigation bar.

Difficulty: 2
Priority: 5

**Comment by irsaris** [comment]
Link the PR to the issue

**Comment by Mark-Anton** [comment]
https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/pull/289
