### ISSUE TITLE
Overseeing UI tasks

### ISSUE THREAD

**Issue by gabrielpadilla7** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#248]
This task focuses on overseeing the design of the UI tasks, making sure that they merge correctly and also that they follow the general style of the website. 

Suggested priority: 4
Suggested difficulty: 5 (due to having to maintain and oversee multiple tasks)

**Comment by gabrielpadilla7** [comment]
@irsaris make sure that whatever PR has UI changes to @ me and add me as a reviewer to check them out and actually oversee the tasks. Thank you! :D

**Comment by irsaris** [comment]
I've seen you been working hard at it so I'll close it now so I dont forget, keep up the good work
