### ISSUE TITLE
[Lecture Topic Task] Follow up on task #33 to document the risk reduction tactic 

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#25]
This task is a response to the professor's feedback on the lack of use of risk reduction tactics.

As discussed in class, one of the risk reduction tactics is implementing requirements to reduce the likelihood of a risk occurring.

Task #33 was created to implement a user guide to reduce the likelihood of one of the risk mentioned in Section 4.5 of the documentation. 

Follow up on this task to document it as an implementation of a countermeasure for a risk reduction tactic

To complete:
Add to the milestone document in section 4.5.3 an explanation of what was done in task #33 and how the implementation of it reduces the likelihood of the risk scenario happening.

**Comment by Keiven-Soto** [comment]
Task completed
