### ISSUE TITLE
Use Decision Table to Improve Documentation

### ISSUE THREAD

**Issue by Adrian-OCS** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#252]
Apply the use of a decision table within the requirements section by finding all combinations of a requirement with complex input conditions in order to find the output conditions in which they result.

**Comment by irsaris** [comment]
Can you expand on this? The description seems lacking.

**Comment by irsaris** [comment]
@Adrian-OCS i need a proper description to accept the task.

**Comment by irsaris** [comment]
@Adrian-OCS once again, managers need a proper description of the task to accept it or it will be nulled by the professor.

**Comment by irsaris** [comment]
This is due in less than 2 hours.
