### ISSUE TITLE
Use Systematic Conflict Management Process to Improve Documentation

### ISSUE THREAD

**Issue by Adrian-OCS** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#253]
Make a new revision of the documentation after some documentation tasks of this milestone are done in order to apply conflict management process.

The systematic process will consist of:
1. identifying overlapping statements
2. detecting conflicts among them and documenting them
3. Generating conflict resolutions
4. Evaluating resolutions and selecting one.

**Comment by irsaris** [comment]
Can you expand on this? The description seems lacking.

**Comment by irsaris** [comment]
@Adrian-OCS i need a proper description to accept the task.

**Comment by irsaris** [comment]
@Adrian-OCS once again, managers need a proper description of the task to accept it or it will be nulled by the professor.

**Comment by Adrian-OCS** [comment]
@irsaris Description added.
