### ISSUE TITLE
[Lecture Topic Task] UI/UX Domain Acquisition Interview Project

### ISSUE THREAD

**Issue by Elielh17** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#257]
Conduct structured interviews with stakeholders (potential users, business analysts, and technical team members) to gather facts about the domain from the perspective of UI/UX requirements. The goal is to understand the expectations, preferences, and pain points of users regarding the software interface and functionality.

**Comment by irsaris** [comment]
This is due in less than 2 hours.

**Comment by JConcepcion01** [comment]
yep, Im refining the text. It'll be done in a few minutes

**Comment by JConcepcion01** [comment]
@irsaris I finished adding everything. Lemme know if anything needs any work
