### ISSUE TITLE
[Lecture Topic Task] Research on the resume standards to ensure relevancy of the resumes and reduce risk

### ISSUE THREAD

**Issue by MrL9000** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#27]
This task is a response to the professor's feedback on the lack of use of risk reduction tactics.

As discussed in class, one of the risk reduction tactics is implementing requirements to reduce the likelihood of a risk occurring.

One of the risks discussed in the documentation was:
Templates provided could be out of date to the current standards of the job market. 
And a countermeasure for it: Periodic research and updates can be done on the current resume standards to ensure the most up to date resumes. 

Follow the countermeasure and research on the industry standards for resumes, if all industries follow the same standards and if our templates follow those standards.

To complete:
Document the results of your research that answers the questions above, in a separate document that you'll link here in a comment. Add to the milestone document in section 4.5.3 an explanation of your research and how the research and the fact our templates follow the industry standards and how your research and implementation of it reduces the likelihood of the risk scenario happening.

**Comment by BryanDVG** [comment]
[Here](https://docs.google.com/document/d/1ymJC84P4R1-eF7sK9gkD_tr_h_anqzt2fR_oILJfd1w/edit) is the document with the corresponding research.

**Comment by Keiven-Soto** [comment]
Task completed

**Comment by PinkSylvie** [comment]
You are not supposed to close your own tasks
