### ISSUE TITLE
[Lecture Topic Task] Security Strategies for Modern Web Applications

### ISSUE THREAD

**Issue by Janiel777** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#271]
## Este LTT se centrará en exponer y describir una serie de estrategias de seguridad esenciales para proteger aplicaciones web modernas. Las explicaciones detalladas se basarán en las tecnologías específicamente seleccionadas para el proyecto (PostgreSQL, React, y Node.js). Aquí se enumeran algunas de las estrategias clave:

- Autenticación Segura

- Control de Acceso Basado en Roles (RBAC)

- Protección contra Inyección SQL

- Mitigación de Ataques Cross-Site Scripting (XSS)

- Defensa contra Cross-Site Request Forgery (CSRF)

- Cifrado de Datos en Reposo y en Tránsito

- Gestión Segura de Sesiones

- Validación y Sanitización de Entradas

- Implementación de Políticas de Seguridad del Contenido (CSP)

- Seguridad en la API y el Endpoint

- Limitación de Tasa de Peticiones (Rate Limiting)

- Auditorías de Seguridad y Escaneo de Vulnerabilidades

- Uso de HTTPS y Certificados TLS

- Actualizaciones y Parches de Seguridad

Cada una de estas estrategias será abordada con explicaciones en base a las tecnologías escogidas, proporcionando una comprensión sólida de cómo aplicarlas efectivamente para asegurar la aplicación web. Este enfoque garantizará que el equipo de desarrollo esté equipado con el conocimiento necesario para implementar prácticas de seguridad robustas y defender la aplicación contra amenazas comunes en el entorno web actual.

Para sustentar la idea de crear el LTT "Estrategias de Seguridad para Aplicaciones Web Modernas", podemos referirnos a la sección sobre "Inspecciones y revisiones de requisitos" del documento [slide05.pdf](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/files/14827751/slide05.pdf). Aquí, se menciona la importancia de guiar la búsqueda de defectos hacia problemas específicos mediante el uso de listas de verificación dirigidas por defectos y específicas de la calidad, que incluyen la seguridad entre las categorías de NFR (Requisitos No Funcionales) consideradas​​. Este enfoque puede aplicarse para destacar la relevancia de tener estrategias de seguridad bien definidas y cómo estas pueden ser verificadas y validadas como parte integral del proceso de aseguramiento de la calidad de los requisitos de software.

**Comment by Janiel777** [comment]
@irsaris Para que revises este LTT y cerrar este issue.

https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/wiki

**Comment by irsaris** [comment]
great work!
