### ISSUE TITLE
Apply Predictive text option for Education

### ISSUE THREAD

**Issue by Adrian-OCS** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#278]
Implement autocomplete on education page within nlp_service.py and educationModals.js files with a button that allows autocomplete of a section when pressed.

**Comment by irsaris** [comment]
@Adrian-OCS once again, managers need a proper description of the task to accept it or it will be nulled by the professor.

**Comment by irsaris** [comment]
This is due in less than 2 hours.

**Comment by irsaris** [comment]
where is the PR?

**Comment by irsaris** [comment]
?
