### ISSUE TITLE
Fill out section "1.3 Scope, Span and Synopsis" found in [UPResuMe] Milestone 1"

### ISSUE THREAD

**Issue by PinkSylvie** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#28]
This section of the documentation is recommended to be filled up alongside each other because to fill up the span you need to understand the scope, and to understand the synopsis you need to understand the scope and span. As such for this task you'll add scope, span and synopsis of teh project into the documentation.

To complete: Add scope, span and synopsis to the documentation, review what you added with the professor, get it approved by managers and link the documentation to a comment in the issue to confirm.

**Comment by PinkSylvie** [comment]
> I have finished adding the sections, please take a look and tell me if I should redo something.

They are not in the document

**Comment by Chosen-Juan1** [comment]
<img width="1440" alt="Screenshot 2024-02-22 at 12 25 55 PM" src="https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/101728824/af099268-3653-4321-8ef1-22bddc76bdfe">

**Comment by PinkSylvie** [comment]
Seems the document hadn't loaded in my side. My bad

**Comment by PinkSylvie** [comment]
> <img width="1440" alt="Screenshot 2024-02-22 at 12 25 55 PM" src="https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/101728824/af099268-3653-4321-8ef1-22bddc76bdfe">
> 
> 
Ok never mind I still can't see it in the document

**Comment by PinkSylvie** [comment]
> > <img width="1440" alt="Screenshot 2024-02-22 at 12 25 55 PM" src="https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/101728824/af099268-3653-4321-8ef1-22bddc76bdfe">
> > 
> > 
> Ok never mind I still can't see it in the document 

Oooh wait wrong project this UPResume lol XD

**Comment by Chosen-Juan1** [comment]
Ah XD. Don't worry, it happens to me as well
