### ISSUE TITLE
[Lecture Topic Task] Implement a small guide on how to use the site to reduce a risk

### ISSUE THREAD

**Issue by BryanDVG** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#33]
This task is a response to the professor's feedback on the lack of use of risk reduction tactics. 

As discussed in class, one of the risk reduction tactics is implementing requirements to reduce the likelihood of a risk occurring. 

One of the risks discussed in the documentation was: 
The platform may not be intuitive or easy to use for users. Likelihood: Intermediate.
And a countermeasure for it: Implementing a comprehensive guide and tutorial section on the website, which give the user the step-by-step instructions on how to create their resume.

Follow the countermeasure to reduce the likelihood of the user being confused on how to use the website. 

To complete:
Implement a small visual that the user can access via clicking something like a help button or a show me how, which explains simply how the resume builder works

**Comment by BryanDVG** [comment]
Difficulty: 5
Urgency: 4

**Comment by Keiven-Soto** [comment]
Task completed
