### ISSUE TITLE
Task: Designing Seamless Integration

### ISSUE THREAD

**Issue by joel-alvarado** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#38]

**Comment by Mark-Anton** [comment]
Objective:  

Primary Goal: Develop a mechanism for seamless synchronization between the editing interface and the preview screen. 

Key Design Considerations:  

Real-Time Synchronization: Implement a system that ensures changes made in the editing interface are instantly reflected in the preview screen. 

Consistent Layout: Design both interfaces with a consistent layout to enhance user orientation and interaction.  

Expected Outcomes:  A synchronization feature that provides real-time feedback and maintains a consistent look and feel between the editing and preview interfaces.

**Comment by Mark-Anton** [comment]
Modified the navigation tool bar to organize both resume template and resume information under a single compact drop down menu with the title of Resume for simplicity and organizing the tool bar.

![image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/42784582/d50a929c-3b4f-4a61-bed0-e45b1b92ca42)

https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/pull/92
