### ISSUE TITLE
Implement Frontend for Signup and Login

### ISSUE THREAD

**Issue by BreannaGSegarra** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#39]
Once the backend for login and signup is completed and the UI design is done, add frontend pages for both of these. This includes the following:

For login:
1. Prompt user for email or username.
2. Prompt user for password.

For signup:
1. Prompt user for email.
2. Prompt user for username.
3. Prompt user for password.
4. Prompt user to retype the password to make sure it matches.

Recommended Priority: 5
Recommended Difficulty: 3

**Comment by JeremySanchez1** [comment]
@BreannaGSegarra @irsaris @Negroni1 

**Task in progress**

**Comment by JeremySanchez1** [comment]
![Image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/71047020/7faddd56-6977-4342-9b78-af52660a536e)



![Image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/71047020/0bfa7b00-bc37-45b4-9214-d44c972df0b0)

**Comment by irsaris** [comment]
Nicely done! Make sure that these are included here https://docs.google.com/document/d/1StfmPGMAUl4LZwA9w4PqyI1FdQ5Lno4EMKGMrhizV6Y/edit#heading=h.h33gjfujaoou
