### ISSUE TITLE
Implement Backend for Signup and Login

### ISSUE THREAD

**Issue by BreannaGSegarra** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#40]
Once the User object has been created and the table has been stored in the database, create the endpoints for user signup and login. This involves the following:

For login:
1. Prompt user for username or email.
2. Prompt user for password.
3. Check that the username or email exists.
4. Check that the password is correct.

For signup:
1. Prompt user for username.
5. Prompt user for email.
6. Prompt user password.
7. Prompt user for re-typed password.
8. Check that re-typed password matches password.
9. Check that user does not already exist.

Recommended Priority: 5
Recommended Difficulty: 4

**Comment by PinkSylvie** [comment]
Will be reaching out to you to work on my task #8
