### ISSUE TITLE
Multiple Language Templates

### ISSUE THREAD

**Issue by BryanDVG** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#43]
Create a language selection to allow users to choose their preferred language for the resume.

**Comment by gabrielpadilla7** [comment]
This task is something that I could do, I could add a spanish language template for starters and other languages may be added too. The website can also be translated too

**Comment by irsaris** [comment]
Hello, is this a task you're still interested in doing?

**Comment by gabrielpadilla7** [comment]
Hello! I'm still interested in doing this task!

**Comment by gabrielpadilla7** [comment]
Difficulty: 5
Urgency: 3

**Comment by irsaris** [comment]
This is due in less than 2 hours.
