### ISSUE TITLE
Add 2.1.6 (Function Signatures) to Documentation

### ISSUE THREAD

**Issue by BreannaGSegarra** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#44]
Add the function signatures section to the document, which has the following specifications:
1. Stresses the importance of contemplating the requirements for executing an action, the necessary information inputs, and the resultant changes or outputs in function signatures.
2. Encourages adapting function signatures to the specific context of the action being performed.
3. Acknowledges that the context may influence the scope of changes, dependencies, and the nature of the result.
4. Recognizes the need to account for possible failures in function signatures.
5. Proposes solutions like using an Option datatype to wrap possible results or provide indicators for failure.
6. Suggests identifying behaviors as sequences of actions with potential dynamic and sequential aspects.
7. Acknowledges the importance of capturing the temporal and process-oriented nature of certain activities in function signatures.

Recommended Priority: 3
Recommended Difficulty: 4

**Comment by irsaris** [comment]
Reminder: the deadline is at 8pm on Friday but we need time to revise. Please complete your part ASAP.
