### ISSUE TITLE
[Lecture Topic Task] Add section [1.1 Team] to the documentation

### ISSUE THREAD

**Issue by joel-alvarado** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#49]
In the context of the project, it's important to distinguish between team members and partners, as they serve different roles:

- **Team Members:** These are individuals directly involved in the project's development and execution. Team members actively contribute to project tasks, bring specific skills, and collaborate closely with one another.

- **Partners:** While every team member is inherently a partner, it's possible to have additional partners who are not part of the core project team. These external partners could include outside experts, clients, stakeholders, or organizations with a vested interest in the project's success.

**Justification for Partner Inclusion:**

- If the project exclusively relies on team members and there are no other external partners, it's essential to justify this absence. This could be due to the self-sufficiency of the team or the project's nature, which doesn't necessitate external partnerships.

**Defining Roles and Responsibilities:**

- Clearly define the roles and responsibilities of each team member and partner. Team members typically have active involvement in project tasks, while external partners may have specialized roles, advisory capacities, or stakeholder interests to consider.

**Distinction from Customers or Users:**

- It's crucial to recognize that customers or users are distinct from partners. Partners generally have a higher level of engagement, involvement, and stake in the project compared to customers or users.

- While customers and users provide valuable insights and feedback, they are not typically considered partners in the same sense as those actively contributing to the project's development and execution.

**Potential Uncontacted Partners:**

- Acknowledge the possibility of uncontacted partners. If there are partners who haven't been engaged yet, document this and consider potential roles and responsibilities they might assume when they become involved.

**Comment by irsaris** [comment]
@joel-alvarado could you mention the managers in the 1.1 section

**Comment by joel-alvarado** [comment]
Manager team added.
