### ISSUE TITLE
Begin construction of the data base's scheme (what it will contain and how will it be implemented).

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#5]
For this task, we will first have to plan what type of information will be stored within (make the scheme) as that will simplify the process of building the tables within the database. After it is planned, the we will have to move over to the implementation (I believe it could be done for this milestone). I suggest the use of PostgreSQL, through a docker image, and Flask for maintaining both the database and the backend portion of the application.

**Comment by Chosen-Juan1** [comment]
The scheme of the data base will be constructed as a Entity Relationship diagram, as it helps us visualize the relationships between tables within SQL. The experience i have with this diagram is a bit limited, so ill have to do some research in order to properly construct one.

**Comment by irsaris** [comment]
Reminder: This task is due today before midnight.

**Comment by Chosen-Juan1** [comment]
it what section do i put it in?

**Comment by irsaris** [comment]
If its a diagram that has to do with implementation, then section 2.3 might be good for that.

**Comment by Chosen-Juan1** [comment]
The scheme has been added to section 2.3, closing the issue.
