### ISSUE TITLE
Navigation and Guidance

### ISSUE THREAD

**Issue by JeremySanchez1** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#53]
- [x] Implement clear navigation menus or breadcrumbs for users to move between different sections of the data entry process.
- [ ] Develop tooltips, help icons, or modal windows that provide users with information on how to fill out the forms.

**Comment by gabrielpadilla7** [comment]
@JeremySanchez1 I think the navigation has already been implemented, unless you'd like me to design one that's more fleshed out. There's a .js file named NavBar.

**Comment by gabrielpadilla7** [comment]
@JeremySanchez1 I could add descriptions when you hover over the buttons if that's what you'd like!

**Comment by JeremySanchez1** [comment]
I see, yeah it appears that this issue overlaps with https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/issues/9.

I'd say that the task can still be viable for pts, if you lean more toward the guidance side of it, like you mentioned. 

Picking parts of the page and adding this type of icon to show what the feature is about.

Icon:
![Image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/71047020/dc3f4b5c-70a5-42ec-8df1-0027fc607a70)

Also for the resume information page, a brief description of what the section is about and what the user could put there. (i.e. Work experience -> "This section is for experiences such as internships, research, etc ...and so on")

**Comment by gabrielpadilla7** [comment]
Perfect! I'll get on it right now!
