### ISSUE TITLE
[Lecture Topic Task] Write 2.2.3 Domain Requirements

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#66]
Domain requirements stem from observations in the domain and the decision to replicate certain phenomena or concepts within a computational system. These requirements derive from properties inherent in the domain, ensuring the system accurately reflects domain characteristics. Conversely, requirements not originating from the domain are termed application requirements, driven by the desire to create a specific application or system. Effective requirements are formulated to mandate specific actions from the system, with language like "must provide means to" preferred over "must allow." Additionally, domain-specific terminology is recommended over generic terms like "user." It's crucial to reference domain properties in requirements to maintain alignment with domain characteristics.

**Comment by irsaris** [comment]
Reminder: the deadline is at 8pm on Friday but we need time to revise. Please complete your part ASAP. @Adrian-OCS
