### ISSUE TITLE
[Lecture Topic Task] Write 2.2.4 interface requirements

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#67]
Interface requirements involve incorporating shared phenomena and concepts from the domain into the system, and managing them within the system. This includes considerations like how to initiate and update concepts like recipes or artworks within the system, as well as the ability to update or edit information about external phenomena. These requirements may have multiple components, including interface-related aspects and broader domain considerations. Ultimately, they stem from the need to represent domain concepts within the system and ensure accurate reflection of changes in the domain.

**Comment by irsaris** [comment]
@Negroni1 there are some bullet points regarding 'the system' which should only be mentioned in machine requirements.
