### ISSUE TITLE
Add Terminology and its relation to Domain Rough Sketch to Documentation (2.1.3)

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#7]
The domain terminology is not part of the rough sketch: to develop the terminology you have to analyze the rough sketch and come up with good definitions for the terms used e.g. in stakeholder interviews. So, the definitions are results of the processing and are therefore not rough. 

Add terminology and its connection to the rough sketch into the document

**Comment by PinkSylvie** [comment]
@Negroni1 @irsaris  @BreannaGSegarra Finished and  added this section to the document and I got this reviewed by the professor today. @ you here so you can review it as well.
