### ISSUE TITLE
[Lecture Topic Task] Add 3.1 Concept Analysis to documentation

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#70]
You always want to start with a rough sketch whether you want to document your domain, your requirements, or whatever else. Documenting the rough sketch allows you to check the steps taken to get to your concepts, abstractions, decisions, etc. Only when you document the initial starting point can you later retrace your steps and check whether you would still take them the same way.
In the concept formation and analysis of your rough sketch you find and introduce concepts that you think arise from the rough sketch. You document your decision to e.g. take the "Toyota Corolla" mentioned by Paul and the "Suzuki Hayabusa" mentioned by Iris and to introduce a concept "Vehicle" and you identify how these are similar for the purpose of your project.
Also in that section you identify potential clashes: maybe someone is using a term in one way and someone else uses the same term in the (slightly?) different way. Are these compatible? Can a common base be found?
When you want to do domain concept analysis you need to take the domain rough sketch (obtained from interviews, common knowledge, literature review, …) and analyze what the common concepts are.

**Comment by PinkSylvie** [comment]
@BreannaGSegarra @irsaris @Negroni1 I added just added this part to the documentation. I made the concept analysis based on the rough sketch I made and the common terms and subjects I saw being brought up by our stakeholders. Whenever you can if you can review it, I'd appreciate it. I showed it to the professor today after class as well and got his ok.

**Comment by PinkSylvie** [comment]
@Adrian-OCS notifying you too that I added the concept analysis to the documentation so you can eye it out and be able to work on the terminology
