### ISSUE TITLE
Export and Download Options

### ISSUE THREAD

**Issue by JonathanDebug** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#73]
Allow users to export their resumes in various formats, such as PDF, Word, or plain text, and download them for printing, emailing, or sharing digitally with potential employers.

**Comment by JonathanDebug** [comment]
i added a code that would let you download files from the website, since the resume creator is not complete yet there is nothing to download until that feature is completed. Until then I added the code to a different file called Download.js, when the feature is completed then the file can be changed and integrated to the main code. I made a different branch for this, should I push the branch? @Negroni1 @irsaris

**Comment by irsaris** [comment]
You can make a pull request and tie it to this issue

**Comment by JonathanDebug** [comment]
I think its done now.

**Comment by irsaris** [comment]
There's not a pull request that has been created nor an issue tied to it, please revise.

**Comment by JonathanDebug** [comment]
#94

**Comment by JonathanDebug** [comment]
This task is got the preview team.
