### ISSUE TITLE
Predictive text option

### ISSUE THREAD

**Issue by irsaris** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#76]
The app will suggest predictive text based on what the user has already written and suggest responses.

**Comment by GaddPetrivoki** [comment]
Could you expand this? Are you referring to just suggesting words you could use like a mobile keyboard? Prompts for an AI to help you write a resume?

**Comment by Janiel777** [comment]
This should have the lowest possible priority and perhaps it should not be in this milestone. Since first we should focus on ensuring that the website has a head and tail.

**Comment by irsaris** [comment]
This would be the implementation in #133.

**Comment by irsaris** [comment]
Reminder: this is due before midnight today.

**Comment by JorgeC08** [comment]
Implemented the Predictive Text feature using Hugging Face, distilgpt2. It should be able to analyze the context of what is written and generate upon that. It can be a little sporadical but works as intended if given enough context. It may need a little of fine tuning in the future.
