### ISSUE TITLE
2.3.1 Selected Fragments of the Implementation

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#80]
Include implementation fragments like source code or diagrams in documentation only when they improve understanding. Use markdown or CodeBlocks for code snippets, and scalable formats like PDF for screen designs. Fragments should complement explanations, not be included for their own sake.

**Comment by JonathanDebug** [comment]
I added the section to the documentation, please review, if all seems good then close it. @Negroni1 @irsaris
