### ISSUE TITLE
Database server

### ISSUE THREAD

**Issue by JorgeC08** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#82]
While setting up some PostgreSQL tables, it became clear we might benefit from a dedicated server for our database. This could streamline our data handling and improve overall project efficiency.

**Comment by Janiel777** [comment]
The cloud database has already been implemented using the ElephantSQL page.

![image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/95184925/eea9d2bd-8a65-4fe5-a1ad-bf9d86ea36f8)
