### ISSUE TITLE
Task: Creating Intuitive Editing Controls

### ISSUE THREAD

**Issue by Negroni1** [uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder#9]

**Comment by Mark-Anton** [comment]
Objective:

Primary Goal: Design intuitive editing controls that are easily accessible and understandable.
Key Design Considerations:

User-Friendly Controls: Implement controls that are easy for users to locate and use effectively.
Responsive Design: Ensure the editing controls adapt to various screen sizes and devices.

Expected Outcomes:

An editing interface with intuitive controls that enhance user experience and productivity, while also being responsive across different devices.

**Comment by Mark-Anton** [comment]
https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/pull/92

![image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-automated-resume-builder/assets/42784582/af51f6b0-6a83-4d74-9a83-1a24d48894d0)

Simplified the user interface of the navigation bar to include the home button icon, User and Resume buttons.
